development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://qfnodcsfcrsjox:NaVsfl9bzBlVDvtadRDVrGsWmx@ec2-54-75-232-66.eu-west-1.compute.amazonaws.com:5432/das0orvs87m4k5
